elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"

bot:
  build: .
  links:
    - elasticsearch
  volumes:
    - ".:/src/app"
  environment:
    - token=xoxb-50511748432-Rztd1yjENcRHpJ9llAfMQbpd
